Sticky Custom Post Types plugin Refactor
svn2github/wordpress-vip-plugins pull request #3
Opened 2018-11-08 20:24 UTC by renatonascalves

This plugin was very useful for a client. This PR is to update it to:

- account for code best practices;
- add the stick class on sticky posts;
- add internationalization;
- Other minor fixes and updates.

2018-11-09 21:29 UTC, rinatkhaziev requested changes
Hi, we reviewed the code, there are some minor escaping issues that need to be fixed.

2018-11-09 21:29 UTC, rinatkhaziev commented on sticky-custom-post-types/sticky-custom-post-types.php
> +				echo '<p>' . __( 'No public custom post types found.', 'sticky-custom-post-types' ) . '</p>'; // WPCS: XSS ok.
Could you please update __ to esc_html__?

2018-11-09 21:29 UTC, rinatkhaziev commented on sticky-custom-post-types/sticky-custom-post-types.php
> +				__( 'Sticky', 'ione3' ),
Looks like `ione3` is a copy-paste that needs to be fixed.

2018-11-09 21:29 UTC, rinatkhaziev commented on sticky-custom-post-types/sticky-custom-post-types.php
> +			echo '<p>' . __( 'Enable support for sticky custom post types.', 'sticky-custom-post-types' ) . '</p>'; // WPCS: XSS ok.
Could you please update __ to esc_html__?

2018-11-19 12:24 UTC, renatonascalves commented on sticky-custom-post-types/sticky-custom-post-types.php
> +				echo '<p>' . __( 'No public custom post types found.', 'sticky-custom-post-types' ) . '</p>'; // WPCS: XSS ok.
Updated!

2018-11-19 12:24 UTC, renatonascalves commented on sticky-custom-post-types/sticky-custom-post-types.php
> +				__( 'Sticky', 'ione3' ),
Sorry! Updated!

2018-11-19 12:24 UTC, renatonascalves commented on sticky-custom-post-types/sticky-custom-post-types.php
> +			echo '<p>' . __( 'Enable support for sticky custom post types.', 'sticky-custom-post-types' ) . '</p>'; // WPCS: XSS ok.
Updated!

2018-11-19 12:32 UTC, renatonascalves commented on sticky-custom-post-types/sticky-custom-post-types.php
> +			$post_types = apply_filters( 'sticky_supported_custom_post_types', $post_types );
This adds a way for developers to remove certain **valid** custom post types programatically.

2018-11-21 14:53 UTC, renatonascalves commented
@rinatkhaziev Could you take another look? =)

2018-11-26 22:39 UTC, rinatkhaziev approved these changes

2018-11-28 18:20 UTC, renatonascalves commented
@rinatkhaziev it seems it was approved for merge [here](https://wordpressvip.zendesk.com/hc/en-us/requests/85505).

=)

2018-12-03 13:06 UTC, renatonascalves commented
For posterity, this PR implementation was added but with a different slug: https://github.com/svn2github/wordpress-vip-plugins/tree/master/sticky-custom-post-types-1.3

Thanks! =)

2018-12-03 13:06 UTC, closed without merging